### PR TITLE
Implement RelationRegistry as a graph

### PR DESCRIPTION
**Pull request by snusnu**
Again, opening this early for us to discuss

### CODE REVIEW

**Comment by snusnu** [comment]
@dkubb @solnic @mbj [Here](http://www.diagram.ly/?share=#Rbibapc8WDKlnAbUCSMiiHMNRXB6WKgd0JyrO9Whc7Di6leeW5) are some sketches of how I imagine the graph to look like when performing some common operations. If the link doesn't work, please [download](https://gist.github.com/gists/3781072/download) the diagram file and perform File/Open at http://www.diagram.ly

**Comment by snusnu** [comment]
Travis is running our integration tests now, and this gives a few new failures in `jruby-19mode` and `rbx-18mode`. I'm not sure if I should set those failures to be allowed for now, or if we should start investigating them.

**Comment by solnic** [comment]
Please disable for now; Will fix later

**Comment by snusnu** [comment]
Closing this one in favor of [this one](https://github.com/solnic/dm-mapper/pull/9)

**Pull request closed without merging**
