### PR TITLE
Add Sqlite3 adapter, analogues to the postgres one.

### PR DESCRIPTION
**Pull request by plexus**
Just a thin wrapper that ties sqlite3: urls to the DataObjects sqlite3 adapter, exactly like the postgres one.

### CODE REVIEW

**Comment by snusnu** [comment]
@arnebrasseur nice! did you try running the specs with sqlite too? i'd imagine they could break altho both postgres and sqlite3 are probably quite standards compliant. In any case, we'll have to start developing other rdbms adapters at some point soon. If you could get specs to run (they can fail, that's not a problem), we could consider pushing this further inside dm-mapper for some time, considering it as a spike.

In the longterm, the various veritas adapters will be extracted into separate gems.

**Comment by plexus** [comment]
Specs are all green on Sqlite3! yay!

I had to change a few things to test against a different backend, see latest commit on the same branch. If you have in `config/database.yml`

``` yaml
sqlite3: 'sqlite:/tmp/dm-mapper_test.sqlite3'
```

Then you can run the specs with

``` bash
DM_REPO_NAME=sqlite3 rspec
```

I tried with in_memory as well but then a bunch of tests fail (unsurprisingly?)

**Comment by snusnu** [comment]
@arnebrasseur Awesome, thx a lot! I'd suggest renaming the env var in use to `DM_ADAPTER`. This is a definite step towards running specs with multiple adapters, so again, thx a lot for this!

I'm not surprised that the in memory specs are failing, as there is no equivalent to `#setup_db' for in memory operations yet. We need to find an abstraction that allows us to either create/seed the base relations accessible via the configured adapter, or the in memory relations.

**Comment by plexus** [comment]
Did as requested. I would suggest to also rename the `:test` repository to `:in_memory` for consistency. I'll have a look at that later, a simple sed replace proved too simple.

Let me know if you'd like me to squash these commits before merging.

**Comment by snusnu** [comment]
@arnebrasseur +1 re changing the `:test` to `:in_memory`. no need to squash the commits.

**Comment by plexus** [comment]
bitte schön

**Comment by snusnu** [comment]
danke schön

**Comment by snusnu** [comment]
@arnebrasseur anything else you feel like adding? i'd be happy to merge it in the current state

**Comment by plexus** [comment]
No, it's good for me like this.

**Comment by snusnu** [comment]
nice, thx again!

**Comment by plexus** [comment]
Awesome, happy to contribute, would love to see this project flourish!

**Pull request merged**
