### PR TITLE
Add missing Attribute::* tests

### PR DESCRIPTION
**Pull request by indrekj**
I'm trying to get more familiar with DM source code. So I added some missing specs.

### CODE REVIEW

**Comment by dkubb** [comment]
@indrekj did you run the tests through mutant to make sure they covered all the possible states of the code?

@snusnu or @solnic will probably need to comment, but the style looks good to me. All of our DM2 gems use similar coding styles in the specs and libs, and this looks really similar to what I've been doing too.

**Comment by indrekj** [comment]
@dkubb Yes, I ran these through mutant. I will fix the failing test in a few hours.

**Comment by dkubb** [comment]
I noticed some integration specs failed, but I'm not sure if they're related to this branch. I checked history and didn't see any previous failures of the same kind, so I wonder if they are due to spec randomization.

@indrekj do you see those same failures under rbx in 1.8 mode? (you have to run it using `ruby -X18 -S bundle exec rake <task>`)

**Comment by indrekj** [comment]
My commits weren't up to date with the latest master branch. I just rebased this branch. But I'm still seeing these errors. I'm also seeing them when running the tests on the master branch with rbx18.

**Comment by solnic** [comment]
Closing this because mapper is being moved to rom-mapper :)

**Pull request closed without merging**
