### PR TITLE
TODO said that there were pending specs so...

### PR DESCRIPTION
**Pull request by elight**
... here's a few less pending specs. ;-)

Anything I should know in response?  Seemed like a safe place to get my feet wet.

### CODE REVIEW

**Comment by solnic** [comment]
Yeah current mapper registry has probably a semi-optimal implementation. It was spiked out (hence lack of proper unit tests). So now we're discovering what needs to be improved. I think this part is safe to work on in isolation from the upcoming refactor as it'll be mostly concerned with the graph and building mappers (unless we want to change registry interface, @snusnu?)

**Comment by solnic** [comment]
@elight oh and btw - THANK YOU :)

**Comment by elight** [comment]
I'll wait for @snusnu to comment before making any other changes.

Any other pointers toward parts of the code that aren't currently being monkeyed with that could use help?  I expect to have some spare cycles over the next few days.

**Comment by solnic** [comment]
@elight let's sync up on IRC bkz there's a ton of work to do in many places (not just dm-mapper). I'm sure either me, @dkubb, @snusnu or @mbj can bring you up to speed :)

**Comment by dkubb** [comment]
@elight I should we should probably all chat in IRC like @solnic mentioned.

These are some of the things I'm working on soonish:

After I finish up axiom-types, which is a tiny lib that extracts some duplicate code in Virtus and Veritas, I have to rename the veritas lib to axiom (which is mostly trivial), finish upgrading the axiom\* gems to use devtools, fix any mutations that mutant brings up.

After this I'm moving onto writing an SQL generator/parser like mbj's cql project. I'll then use the SQL generator within veritas-sql-generator. Then I'll write something that can simplify the SQL so that we end up with as clean SQL as possible. The general goal is that SQL should resemble something relatively close to what we'd write by hand. Right now what's generated is correct (verified by hand, fuzzed, etc), but there has been some question that it's not as readable as it should be. There may also be some perf issues with databases having not-so-good optimizers.

At some point I have to update the (axiom|veritas)-do-adapter to propagate writes on the relation to the database, as well as adding the nest/unnest RA functions to (axiom|veritas).

**Comment by solnic** [comment]
@dkubb it's _awesome_ to hear you're planning to tackle SQL generator! What's your estimate on that task? Also can we somehow work on propagating writes to db in do-adapter simultaneously? (I can work on that but I'll need your guidance)

**Comment by plexus** [comment]
I'd also be interested to help out a bit here and there. Is there a time of
day when IRC is typically most active? What time zone are people in?

**Comment by solnic** [comment]
me, @snusnu and @mbj are hanging out there all the time during the day and evening…CEST :)

## 

# solnic

**Comment by plexus** [comment]
You guys are already on summer time? Awesome :)

**Comment by solnic** [comment]
ugh sorry I meant CET - no summer time just yet :)

**Comment by mbj** [comment]
@dkubb It was an AQL not CQL generator ;) I'd love to build a CQLveritas-cassandra-adapter one, but did not find a sponsor or another way to pay my bills ;)

**Comment by snusnu** [comment]
@elight hey, sorry for getting back so late and even now not being able to really answer your questions / give you more guidelines. I'd suggest dropping into IRC when you have some time, and just ping me or leave me a memo. There's a planned refactoring ahead which will pretty much touch every single part of dm-mapper, so i'm not sure if right now is a good time to start contributing by adding specs. There's tons of other things to do tho, and i'd be happy to discuss them with you

@arnebrasseur same goes for you, just ping me in IRC

i'll be online tomorrow starting around noon CET

**Comment by elight** [comment]
Will do.

Wow. This project still has some of the nicest leads on any OSS project I've seen. Mind blowing.

Glad I recommended to folks at ROA looking to get into OSS to visit DM.

**Comment by solnic** [comment]
Closing this because mapper is being moved to rom-mapper.

**Pull request closed without merging**
