### PR TITLE
WIP: Refactoring integration specs

### PR DESCRIPTION
**Pull request by cored**

### CODE REVIEW

**Comment by snusnu** [comment]
@cored yeah you're right. ideally we'd get all order dependent expectations in integration specs rewritten to the style you've used in your commit. `songs.first` definitely is such an order dependency, we want that to go away.

**Comment by snusnu** [comment]
@cored looking at the travis timeout failures, could you increase the unit_test_timeout to 1.0 in `config/devtools.yml`?

**Comment by snusnu** [comment]
@mbj we need a solution for that .... ;)

**Comment by solnic** [comment]
oh for ffs this is exactly what I was talking about. Please remove this timeout.

**Comment by snusnu** [comment]
@cored awesome, thx! one more minor thing (nothing to change for this PR): could you please try to keep your commit messages short (i.e. the first line with 60chars or so, and if necessary, followed by a blank line plus a more detailed description). That's the style we use throughout the projects, and while being a general "git guideline", it makes for much nicer display on github too.

**Comment by snusnu** [comment]
@solnic imo the timeout is a nice idea. we only need an implementation that only measures CPU time! and we need it soon ;)

**Comment by snusnu** [comment]
@cored thx a lot!

**Pull request merged**
