### PR TITLE
Simplify relationship mapper builder

### PR DESCRIPTION
**Pull request by solnic**
I suspect @snusnu won't like it but this branch removes the concept of joining from target-to-source as I found it uber-complex adding a lot of noise and unneeded complexity. It also makes the graph look awkward by creating nodes that are not inline with mapper and relationship definitions. This whole thing is not worth the effort as it gives very small benefit of theoretically simplifying multi-include. I'm saying theoretically as I realized it only sounds good in theory but in practice it actually makes things harder.

This commit removes 137 LOC and I believe it can still be made if simpler.

I will experiment with multi-include soon to prove my point...

[edit] one more thing, here's a related gist showing target-to-source vs source-to-target in veritas: https://gist.github.com/b369487e7d99b1292337

### CODE REVIEW

**Comment by snusnu** [comment]
@solnic I'm not in favor of target-to-source for the sake of it, and you know it ;)

At the time I just thought that it would simplify multi-include, and how it would exactly complicate that (and only that), still bares explanation, at least for the veritas case. I suspect tho, that you are saying that because it complicates arel, and we obviously want to avoid that. Of course I'm all in favor for everything that simplifies the codebase while still supporting all planned features. I'm very sure that there are ways of doing multi-include with source-to-target, especially when we start relying on graph traversal more. It's clear that we can perform the join without including the same relation more than once, my thinking with target-to-source just was that it would be _very_ easy as we would just need to join all previously prepared relations (that don't include source already). Of course, at the time I didn't know about arel and how it needs different handling. I recognized the fact that the queries for target-to-source don't look especially nice very early on, but correctness was the primary concern.

That being said, I think that it won't be hard to implement multi-include source-to-target. We probably need to perform more joins as compared to target-to-source (as the needed relations aren't defined already), but that doesn't matter.

I'm all in favor of this PR. It simplifies things, so it's a win!

PS: I forked the gist you linked, and updated the target-to-source.rb file to make it look like I imagined it. That doesn't mean that I still insist on target-to-source, it's just for reference. To further strenghten that, why not merge these commits to master right away?

**Comment by solnic** [comment]
Actually it also makes veritas multi-include harder. See that gist for an example. If we were to simplify this we'd have to split all prepared joins into pieces and look for relations that are duplicated to make sure we only join unique ones. This could be solved by optimizer I suppose but even if it was I still don't like complexity around target-to-source approach.

Anyhow. I'm happy you agree here. I will merge this in soon. Oh and please remember arel is not the only reason! :)

**Comment by snusnu** [comment]
@solnic Again, I'm happy with the changes. I don't understand the target-to-source.rb file in your gist tho. I already mentioned that I forked it and updated it to look like I imagined. I already had code that fetched all connectors that would've pointed to the joined relations excluding source. multi-include looked it like it was a matter of iterating over those joined relations, joining them all with source (i.e. perform n joins where n is the number of relationships included). Forked gist is at: https://gist.github.com/037b98c639991a10cd8d

Anyhow. I already said that I like the changes, so much in fact, that I want to start simplifying the builder some more. We agree that arel will need no specific builder, right? So for one, there's no reason for the builder, to expose any public methods, as we aren't subclassing it anymore, right? I have time to do some coding now, and I want to get this into master. Are you fine with that?

**Comment by snusnu** [comment]
@solnic The reason I want to have this in master soon, is because I want to keep working on inferring `:via` and inferring/providing `:source_key` and `:target_key`.

**Comment by solnic** [comment]
Yeah feel free to merge it in :)

## 

solnic

**Pull request merged**
