### PR TITLE
Relationship DSL api ideas

### PR DESCRIPTION
**Pull request by snusnu**
This should serve only as a place to discuss how a possible relationship dsl might look like.

This PR is **NOT** intended to be merged!

Current suggestions can be found [here](https://github.com/solnic/dm-mapper/blob/relationship-dsl-ideas/relationship_dsl.rb) and in comments.

### CODE REVIEW

**Comment by snusnu** [comment]
For the record, I think that i prefer `OPTION 4` atm.

**Comment by dkubb** [comment]
This is kind of how I had envisioned the API looking for the mappers and relationships:

``` ruby
class SongMapper

  has 0..n, :song_tags, SongTag do |song_tag|
    # operation applies to current relation when no "through" specified
    rename(:id => :song_id).join(song_tag)
  end

  has 0..n, :tags, Tag, :through => :song_tags do |tag|
    # operation applies to "through" relation
    join(tag.rename(:id => :tag_id, :name => :tag_name))
  end

  has 0..n, :recent_tags, :through => :tags do
    # operation applies to "through" relation
    restrict { |r| r.song_tag_created_at.gte(Date.today - 7) }

    # NOTE: this assumes song_tags has renamed the created_at above, I
    # omited it for brevity in the example
  end

  has 0..n, :recent_good_tags, :through => :tags do
    # operation applies to "through" relation
    restrict { |r| r.tag_name.eq('good') }
  end

end
```

**Comment by solnic** [comment]
@dkubb this is how it already works. we automatically join prior executing the block though so there's no need to do that manually. Relations have proper headers too with prefixed attributes so your examples with restrictions should just work.

**Comment by dkubb** [comment]
@solnic good to know. It makes sense to me that we could optimize the rename and join operations since they are by far the common case.

@snusnu I saw your comment in IRC about not understanding what `:through` was here. Keep in mind this was just a rough thought, but I was thinking that `:through` would basically just specify what the operations are applied against within the block. It'd be `self` by default. Maybe the word `:through` isn't right though. Maybe `:using` or `:on` is better?

One other option is that since you would have to piggyback over an existing relationship, you wouldn't necessarily need to use `:through` / `:using` / `:on` with a Symbol, but you could use the relationship name, eg:

``` ruby
class SongMapper

  has 0..n, :song_tags, SongTag

  has 0..n, :tags, Tag, :through => song_tags

  has 0..n, :recent_tags, :through => tags do
    # operation applies to "through" relation
    restrict { |r| r.song_tag_created_at.gte(Date.today - 7) }

    # NOTE: this assumes song_tags has renamed the created_at above, I
    # omited it for brevity in the example
  end

  has 0..n, :recent_good_tags, :through => tags do
    # operation applies to "through" relation
    restrict(:tag_name => 'good')
  end

end
```

**Comment by solnic** [comment]
I like option 1. I wouldn't be worried about code alignment. Also I guess we could ditch mapper class as a required argument since we can infer it from the relationship name - this would make the line shorter. Also, in most of the cases we _will_ be inferring the keys automatically. I imagine that `:via` option will only be needed in case of non-standard schemas (legacy dbs).

Regarding "operations on intermediaries can only be applied on the intermediary relationships" - this is a good thing. I would expect it to work like that (it works like that now actually).

We also need to remember that _if_ you are providing `:via` option then you actually have a reason to do so and you _know_ what you're doing so it _is_ obvious to you that the key names are referring to the intermediary and the target. Which means that I wouldn't be worried that it's not explicit enough.

Blocks are more explicit but it feels too complicated that's why I like simple hash options. I thought we'd need blocks for defining how things join but now I changed my mind :P

**Comment by solnic** [comment]
Closing because you know why

**Pull request closed without merging**
